# Build an OpenSuse Leap image and upload it to Vagrant Cloud
# when a new tag is pushed

name: Build and upload using Packer

on:
  push:
    tags: ['v[0-9].[0-9]+.[0-9]+']

jobs:
  build:
    # Vagrant and VirtualBox are already installed in macos runner
    runs-on: macos-latest

    env:
      PKR_VAR_version: ${{ github.ref_name }}
      PKR_VAR_cloud_token: ${{ secrets.VAGRANT_CLOUD_TOKEN }}

    steps:
      - name: Git Checkout
        uses: actions/checkout@v3

      - name: Setup `packer`
        uses: hashicorp/setup-packer@main
        id: setup
        with:
          version: "latest"

      - name: Run `packer init`
        id: init
        run: "packer init ."

      - name: Run `packer validate`
        id: validate
        run: "packer validate ."

      - name: Run `packer build`
        id: build
        run: "packer build ."
